# Generated by Django 2.0.5 on 2018-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, verbose_name='Country Code')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('place_name', models.CharField(max_length=180, verbose_name='Place Name')),
                ('admin_name1', models.CharField(max_length=100, verbose_name='1st order subdivision (state) name')),
                ('admin_code1', models.CharField(max_length=20, verbose_name='1st order subdivision (state) code')),
                ('admin_name2', models.CharField(max_length=100, verbose_name='2nd order subdivision (county/province) name')),
                ('admin_code2', models.CharField(max_length=20, verbose_name='2nd order subdivision (county/province) code')),
                ('admin_name3', models.CharField(max_length=100, verbose_name='3rd order subdivision (community) name')),
                ('admin_code3', models.CharField(max_length=20, verbose_name='3rd order subdivision (community) code')),
                ('latitude', models.FloatField(verbose_name='estimated latitude (wgs84)')),
                ('longitude', models.FloatField(verbose_name='estimated longitude (wgs84)')),
                ('accuracy', models.IntegerField(blank=True, default=0, verbose_name='accuracy of lat/lng from 0=missing then 1=estimated to 6=centroid')),
            ],
            options={
                'verbose_name': 'GeoName',
                'verbose_name_plural': 'GeoNames',
                'ordering': ('country_code', 'postal_code'),
            },
        ),
    ]
